// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponse_bool_ = {
  success?: boolean
  code?: number
  message?: string
  data?: boolean | null
  meta?: {
    [key: string]: unknown
  } | null
}

export type ApiResponse_ItemPublic_ = {
  success?: boolean
  code?: number
  message?: string
  data?: ItemPublic | null
  meta?: {
    [key: string]: unknown
  } | null
}

export type ApiResponse_list_ItemPublic__ = {
  success?: boolean
  code?: number
  message?: string
  data?: Array<ItemPublic> | null
  meta?: {
    [key: string]: unknown
  } | null
}

export type ApiResponse_list_UserPublic__ = {
  success?: boolean
  code?: number
  message?: string
  data?: Array<UserPublic> | null
  meta?: {
    [key: string]: unknown
  } | null
}

export type ApiResponse_NoneType_ = {
  success?: boolean
  code?: number
  message?: string
  data?: null
  meta?: {
    [key: string]: unknown
  } | null
}

export type ApiResponse_Token_ = {
  success?: boolean
  code?: number
  message?: string
  data?: Token | null
  meta?: {
    [key: string]: unknown
  } | null
}

export type ApiResponse_UserPublic_ = {
  success?: boolean
  code?: number
  message?: string
  data?: UserPublic | null
  meta?: {
    [key: string]: unknown
  } | null
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  created_at?: string
  updated_at?: string
  title: string
  description?: string | null
  is_public?: boolean
}

export type ItemPublic = {
  created_at?: string
  updated_at?: string
  title: string
  description?: string | null
  is_public?: boolean
  id: string
  owner: UserPublic
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
  is_public?: boolean | null
}

export type PasswordResetConfirm = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UserCreate = {
  created_at?: string
  updated_at?: string
  email?: string | null
  full_name?: string | null
  is_active?: boolean
  is_superuser?: boolean
  password: string
}

export type UserPublic = {
  created_at?: string
  updated_at?: string
  email?: string | null
  full_name?: string | null
  is_active?: boolean
  is_superuser?: boolean
  id: string
}

export type UserUpdate = {
  email?: string | null
  full_name?: string | null
  is_active?: boolean | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ApiResponse_list_ItemPublic__

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ApiResponse_ItemPublic_

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ApiResponse_ItemPublic_

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ApiResponse_ItemPublic_

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = ApiResponse_NoneType_

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = ApiResponse_Token_

export type LoginTestTokenResponse = ApiResponse_UserPublic_

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = ApiResponse_NoneType_

export type LoginResetPasswordData = {
  requestBody: PasswordResetConfirm
}

export type LoginResetPasswordResponse = ApiResponse_NoneType_

export type LoginRecoverPasswordHtmlContentData = {
  args: unknown
  email: string
  kwargs: unknown
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = ApiResponse_list_UserPublic__

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = ApiResponse_UserPublic_

export type UsersReadUserMeResponse = ApiResponse_UserPublic_

export type UsersDeleteUserMeResponse = ApiResponse_NoneType_

export type UsersUpdateUserMeData = {
  requestBody: UserUpdate
}

export type UsersUpdateUserMeResponse = ApiResponse_UserPublic_

export type UsersUpdatePasswordMeData = {
  requestBody: PasswordResetConfirm
}

export type UsersUpdatePasswordMeResponse = ApiResponse_NoneType_

export type UsersRegisterUserData = {
  requestBody: UserCreate
}

export type UsersRegisterUserResponse = ApiResponse_UserPublic_

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = ApiResponse_UserPublic_

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = ApiResponse_UserPublic_

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = ApiResponse_NoneType_

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = ApiResponse_NoneType_

export type UtilsHealthCheckResponse = ApiResponse_bool_
